name: flutterapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17
  liquid_swipe: ^3.0.0
  get:
  smooth_page_indicator: ^1.0.1
  otp_text_field: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/books.jpeg
  image_dark: assets/images/books.jpeg

  android_12:
    image: assets/images/books.jpeg
    icon_background_color: "#ffffff"
    image_dark: assets/images/books.jpeg
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/register.png
    - assets/images/login.png
    - assets/images/top_background.png
    - assets/images/top_background1.png
    - assets/images/top_background2.png
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/men.png